### ISSUE TITLE
Deploy Github Runners into build cluster

### ISSUE THREAD

**Issue by moshloop** [flanksource/vsphere-lab#8]

**Comment by philipstaffordwood** [comment]
base image `sanderknape/github-runner:latest` missing `ping`:

<pre><font color="#8AE234"><b>philip@silent</b></font>:<font color="#729FCF"><b>/code/flanksource/vsphere-lab-issue-7-build-cluster/build-cluster</b></font>$ kubectl logs --tail=50 -lapp=github-runner
/home/github/_work/_update.sh: line 31: ping: command not found
/home/github/_work/_update.sh: line 31: ping: command not found
/home/github/_work/_update.sh: line 31: ping: command not found
/home/github/_work/_update.sh: line 31: ping: command not found
/home/github/_work/_update.sh: line 31: ping: command not found
/home/github/_work/_update.sh: line 31: ping: command not found
</pre>

**Comment by philipstaffordwood** [comment]
First run on new repo without active workflow and runners fails with:
```
# Authentication

Http response code: UnprocessableEntity from 'POST https://api.github.com/repos/philipstaffordwood/karina/actions-runners/registration'
{"message":"Validation Failed","documentation_url":"https://developer.github.com/v3"}
Response status code does not indicate success: 422 (Unprocessable Entity).
An error occurred: Not configured
```
see related issue on gh actions runner: https://github.com/actions/runner/issues/487
